### PR TITLE
Fixed #107 - Fixed issues on createFromDTO with JSON payload

### LINKED ISSUE #107: TransactionMapping fromDTO fails to load transactions
1. Expected behavior and actual behavior.

Using ``TransactionMapping`` class we can create Transactions using the DTO format. Once we turn a transaction to DTO, and try to recreate it using  ``TransactionMapping.fromDTO(transaction.toJSON())`` we get the following error:

> TypeError: Cannot read property 'type' of undefined from \nem2sdk\dist\src\infrastructure\transaction\CreateTransactionFromDTO.js:60:36.

2. Steps to reproduce the problem.

``` typescript
    const transferTransaction = TransferTransaction.create(
        Deadline.create(),
        Address.createFromRawAddress('SAGYCE-QM5SK2-TGFUC5-Z5GZJR-ATKTBS-UQQMMH-KW5B'),
        [NetworkCurrencyMosaic.createRelative(10)],
        PlainMessage.create('hello'),
        NetworkType.MIJIN_TEST
    );
    TransactionMapping.createFromDTO(transferTransaction.toJSON());
```

### PR DESCRIPTION
**Pull request by rg911**
Issue: #107 

Fixed a few issues with createFromDTO

### CODE REVIEW

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts [hunk 1]
```diff
@@ -118,17 +118,27 @@ export const CreateTransactionFromDTO = (transactionDTO): Transaction => {
  */
 const CreateStandaloneTransactionFromDTO = (transactionDTO, transactionInfo): Transaction => {
     if (transactionDTO.type === TransactionType.TRANSFER) {
+        /**
```
Comment (rg911) [inline src/infrastructure/transaction/CreateTransactionFromDTO.ts]: Not 100% sure if this is the best approach. Basically, if user uses serialisation method `toJson()' it will create a `Message` object rather than encoded message (from the rest endpoint for example). Open for suggestions

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts [hunk 2]
```diff
@@ -349,20 +372,29 @@ const extractTransactionVersion = (version: number): number => {
...
  */
-const extractRecipient = (recipient: string): Address | NamespaceId => {
-    // If bit 0 of byte 0 is not set (like in 0x90), then it is a regular address.
-    // Else (e.g. 0x91) it represents a namespace id which starts at byte 1.
-    const bit0 = convert.hexToUint8(recipient.substr(1, 2))[0];
+const extractRecipient = (recipient: any): Address | NamespaceId => {
+    if (typeof recipient === 'string') {
+        // If bit 0 of byte 0 is not set (like in 0x90), then it is a regular address.
+        // Else (e.g. 0x91) it represents a namespace id which starts at byte 1.
+        const bit0 = convert.hexToUint8(recipient.substr(1, 2))[0];
```
Comment (rg911) [inline src/infrastructure/transaction/CreateTransactionFromDTO.ts]: similar to `PlainMessage` when just toJSON method, it will create either a Address object  or NamespaceId object rather than hex value. Open for suggestion as well

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts (hunk 1 above)
Comment (evias) [reply src/infrastructure/transaction/CreateTransactionFromDTO.ts]: As proposed on slack, this could be solved in a `extractMessage` auxiliary class.

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts [hunk 3]
```diff
@@ -118,17 +118,27 @@ export const CreateTransactionFromDTO = (transactionDTO): Transaction => {
  */
 const CreateStandaloneTransactionFromDTO = (transactionDTO, transactionInfo): Transaction => {
     if (transactionDTO.type === TransactionType.TRANSFER) {
+        /**
+         * Check if message is encoded (from DTO) or is raw (from JSON)
+         */
+        let message = EmptyMessage;
+        if (transactionDTO.message !== undefined && convert.isHexString(transactionDTO.message.payload)) {
+            message = PlainMessage.createFromDTO(transactionDTO.message.payload);
```
Comment (evias) [inline src/infrastructure/transaction/CreateTransactionFromDTO.ts]: Can you rename to `createFromPayload` ? it is clearer in usage

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts [hunk 4]
```diff
@@ -349,20 +372,29 @@ const extractTransactionVersion = (version: number): number => {
...
-    // read address from encoded hexadecimal notation
-    return Address.createFromEncoded(recipient);
+        // read address from encoded hexadecimal notation
+        return Address.createFromEncoded(recipient);
+    } else if (typeof recipient === 'object') { // Is JSON object
+        if (recipient.hasOwnProperty('address')) {
+            return Address.createFromRawAddress(recipient.address);
+        }
+
+        return new NamespaceId(recipient.id);
```
Comment (evias) [inline src/infrastructure/transaction/CreateTransactionFromDTO.ts]: make sure to check `recipient.id` is available as well no ? (add it in `else if ..`).

There is a throw afterwards but in case `recipient.id` is not present, it will not throw.

File: src/infrastructure/transaction/CreateTransactionFromDTO.ts (hunk 3 above)
Comment (rg911) [reply src/infrastructure/transaction/CreateTransactionFromDTO.ts]: 👍

Comment (rg911) [reply src/infrastructure/transaction/CreateTransactionFromDTO.ts]: Done!
